In [1]:
from dfm_sp import sp_update_nowcast , Options

series = "GDPC1"
period = "2016q4"
# 
vintage_old = "2016-12-16"
vintage_new = "2016-12-23"
sample_start = "2000-01-01"
country = "US"
spec_file_name = "Spec_US_example.xls"
max_iter = 5000

options_baseline = Options(

    vintage=vintage_old,
    max_iter=max_iter,
    spec_file_name=spec_file_name,
    threshold=1e-4,
    country=country,
    sample_start=sample_start,
    use_cache=True,
)

result_dict = sp_update_nowcast(options_baseline, vintage_new, series, period)

Executing Baseline for 2016-12-16...

 Table 1: Model specification

              SeriesID                   SeriesName                 Units  \
0               PAYEMS           Payroll Employment  Thousands of Persons
1               JTSJOL                 Job Openings             Thousands
2             CPIAUCSL         Consumer Price Index                 Index
3              DGORDER         Durable Goods Orders           $, Millions
4                RSAFS                 Retail Sales           $, Millions
5               UNRATE            Unemployment Rate                     %
6                HOUST               Housing Starts    Thousands of Units
7               INDPRO        Industrial Production                 Index
8              DSPIC96              Personal Income   Chained $, Billions
9              BOPTEXP                      Exports           $, Millions
10             BOPTIMP                      Imports           $, Millions
11             TTLCONS        Construction Spending           $, Millions
12                  IR           Import Price Index                 Index
13            CPILFESL    Core Consumer Price Index                 Index
14            PCEPILFE         Core PCE Price Index                 Index
15               PCEPI              PCE Price Index                 Index
16              PERMIT             Building Permits    Thousands of Units
17                 TCU    Capacity Utilization Rate                     %
18              BUSINV         Business Inventories           $, Millions
19                  IQ           Export Price Index                 Index
20   GACDISA066MSFRBNY       Empire State Mfg Index                 Index
21              PCEC96    Real Consumption Spending   Chained $, Billions
22  GACDFSA066MSFRBPHI   Philadelphia Fed Mfg Index                 Index
23               GDPC1  Real Gross Domestic Product   Chained $, Billions
24              ULCNFB              Unit Labor Cost                 Index

                UnitsTransformed
0            Change (Difference)
1            Change (Difference)
2                 Percent Change
3                 Percent Change
4                 Percent Change
5            Change (Difference)
6                 Percent Change
7                 Percent Change
8                 Percent Change
9                 Percent Change
10                Percent Change
11                Percent Change
12                Percent Change
13                Percent Change
14                Percent Change
15                Percent Change
16           Change (Difference)
17           Change (Difference)
18                Percent Change
19                Percent Change
20    Levels (No Transformation)
21                Percent Change
22    Levels (No Transformation)
23  Percent Change (Annual Rate)
24  Percent Change (Annual Rate)
2000-01-01 00:00:00




Table 2: Data Summary

N =     25 data series
T = 204 observations from 2000-01-01 to 2016-12-01

                                                 Observations  \
Payroll Employment [PAYEMS]                             203.0
Job Openings [JTSJOL]                                   190.0
Consumer Price Index [CPIAUCSL]                         203.0
Durable Goods Orders [DGORDER]                          202.0
Retail Sales [RSAFS]                                    203.0
Unemployment Rate [UNRATE]                              203.0
Housing Starts [HOUST]                                  203.0
Industrial Production [INDPRO]                          203.0
Personal Income [DSPIC96]                               202.0
Exports [BOPTEXP]                                       202.0
Imports [BOPTIMP]                                       202.0
Construction Spending [TTLCONS]                         202.0
Import Price Index [IR]                                 203.0
Core Consumer Price Index [CPILFESL]                    203.0
Core PCE Price Index [PCEPILFE]                         202.0
PCE Price Index [PCEPI]                                 202.0
Building Permits [PERMIT]                               203.0
Capacity Utilization Rate [TCU]                         203.0
Business Inventories [BUSINV]                           202.0
Export Price Index [IQ]                                 203.0
Empire State Mfg Index [GACDISA066MSFRBNY]              186.0
Real Consumption Spending [PCEC96]                      202.0
Philadelphia Fed Mfg Index [GACDFSA066MSFRBPHI]         204.0
Real Gross Domestic Product [GDPC1]                      67.0
Unit Labor Cost [ULCNFB]                                 67.0

                                                Observation Time Range  \
Payroll Employment [PAYEMS]                        Jan-2000 / Nov-2016
Job Openings [JTSJOL]                              Jan-2001 / Oct-2015
Consumer Price Index [CPIAUCSL]                    Jan-2000 / Nov-2016
Durable Goods Orders [DGORDER]                     Jan-2000 / Oct-2016
Retail Sales [RSAFS]                               Jan-2000 / Nov-2016
Unemployment Rate [UNRATE]                         Jan-2000 / Nov-2016
Housing Starts [HOUST]                             Jan-2000 / Nov-2016
Industrial Production [INDPRO]                     Jan-2000 / Nov-2016
Personal Income [DSPIC96]                          Jan-2000 / Oct-2016
Exports [BOPTEXP]                                  Jan-2000 / Oct-2016
Imports [BOPTIMP]                                  Jan-2000 / Oct-2016
Construction Spending [TTLCONS]                    Jan-2000 / Oct-2016
Import Price Index [IR]                            Jan-2000 / Nov-2016
Core Consumer Price Index [CPILFESL]               Jan-2000 / Nov-2016
Core PCE Price Index [PCEPILFE]                    Jan-2000 / Oct-2016
PCE Price Index [PCEPI]                            Jan-2000 / Oct-2016
Building Permits [PERMIT]                          Jan-2000 / Nov-2016
Capacity Utilization Rate [TCU]                    Jan-2000 / Nov-2016
Business Inventories [BUSINV]                      Jan-2000 / Oct-2016
Export Price Index [IQ]                            Jan-2000 / Nov-2016
Empire State Mfg Index [GACDISA066MSFRBNY]         Jul-2001 / Jun-2015
Real Consumption Spending [PCEC96]                 Jan-2000 / Oct-2016
Philadelphia Fed Mfg Index [GACDFSA066MSFRBPHI]    Jan-2000 / Dec-2016
Real Gross Domestic Product [GDPC1]                Mar-2000 / Jul-2005
Unit Labor Cost [ULCNFB]                           Mar-2000 / Jul-2005

                                                        Units  Frequency  \
Payroll Employment [PAYEMS]                      Level change    Monthly
Job Openings [JTSJOL]                            Level change    Monthly
Consumer Price Index [CPIAUCSL]                         Index    Monthly
Durable Goods Orders [DGORDER]                          MoM %    Monthly
Retail Sales [RSAFS]                                    MoM %    Monthly
Unemployment Rate [UNRATE]                        Ppt. change    Monthly
Housing Starts [HOUST]                                  MoM %    Monthly
Industrial Production [INDPRO]                          Index    Monthly
Personal Income [DSPIC96]                               MoM %    Monthly
Exports [BOPTEXP]                                       MoM %    Monthly
Imports [BOPTIMP]                                       MoM %    Monthly
Construction Spending [TTLCONS]                         MoM %    Monthly
Import Price Index [IR]                                 Index    Monthly
Core Consumer Price Index [CPILFESL]                    Index    Monthly
Core PCE Price Index [PCEPILFE]                         Index    Monthly
PCE Price Index [PCEPI]                                 Index    Monthly
Building Permits [PERMIT]                        Level change    Monthly
Capacity Utilization Rate [TCU]                   Ppt. change    Monthly
Business Inventories [BUSINV]                           MoM %    Monthly
Export Price Index [IQ]                                 Index    Monthly
Empire State Mfg Index [GACDISA066MSFRBNY]              Index    Monthly
Real Consumption Spending [PCEC96]                      MoM %    Monthly
Philadelphia Fed Mfg Index [GACDFSA066MSFRBPHI]         Index    Monthly
Real Gross Domestic Product [GDPC1]                  QoQ AR %  Quarterly
Unit Labor Cost [ULCNFB]                                Index  Quarterly

                                                      mean         std  \
Payroll Employment [PAYEMS]                      70.679803  226.807855
Job Openings [JTSJOL]                             4.200000  235.476107
Consumer Price Index [CPIAUCSL]                   0.178791    0.308633
Durable Goods Orders [DGORDER]                    0.203692    4.644054
Retail Sales [RSAFS]                              0.274444    1.056307
Unemployment Rate [UNRATE]                        0.002956    0.166772
Housing Starts [HOUST]                            0.120694    8.305086
Industrial Production [INDPRO]                    0.046291    0.668858
Personal Income [DSPIC96]                         0.196224    0.839956
Exports [BOPTEXP]                                 0.404726    1.793026
Imports [BOPTIMP]                                 0.382928    2.272407
Construction Spending [TTLCONS]                   0.203386    1.209455
Import Price Index [IR]                           0.115838    1.418042
Core Consumer Price Index [CPILFESL]              0.164293    0.079718
Core PCE Price Index [PCEPILFE]                   0.142741    0.093833
PCE Price Index [PCEPI]                           0.152290    0.209249
Building Permits [PERMIT]                        -2.374384   60.433400
Capacity Utilization Rate [TCU]                  -0.035468    0.525887
Business Inventories [BUSINV]                     0.232812    0.581099
Export Price Index [IQ]                           0.100061    0.690716
Empire State Mfg Index [GACDISA066MSFRBNY]        7.676882   14.550804
Real Consumption Spending [PCEC96]                0.183940    0.365878
Philadelphia Fed Mfg Index [GACDFSA066MSFRBPHI]   4.995588   15.010434
Real Gross Domestic Product [GDPC1]               1.865691    2.470982
Unit Labor Cost [ULCNFB]                          1.450529    5.404362

                                                        min  \
Payroll Employment [PAYEMS]                     -823.000000
Job Openings [JTSJOL]                           -727.000000
Consumer Price Index [CPIAUCSL]                   -1.770548
Durable Goods Orders [DGORDER]                   -18.436517
Retail Sales [RSAFS]                              -3.671862
Unemployment Rate [UNRATE]                        -0.500000
Housing Starts [HOUST]                           -18.891916
Industrial Production [INDPRO]                    -4.302911
Personal Income [DSPIC96]                         -6.226424
Exports [BOPTEXP]                                 -7.662287
Imports [BOPTIMP]                                -11.548770
Construction Spending [TTLCONS]                   -4.053791
Import Price Index [IR]                           -7.407407
Core Consumer Price Index [CPILFESL]              -0.112278
Core PCE Price Index [PCEPILFE]                   -0.549946
PCE Price Index [PCEPI]                           -1.131262
Building Permits [PERMIT]                       -259.000000
Capacity Utilization Rate [TCU]                   -3.400000
Business Inventories [BUSINV]                     -2.112722
Export Price Index [IQ]                           -3.188880
Empire State Mfg Index [GACDISA066MSFRBNY]       -34.500000
Real Consumption Spending [PCEC96]                -1.031872
Philadelphia Fed Mfg Index [GACDFSA066MSFRBPHI]  -40.900000
Real Gross Domestic Product [GDPC1]               -8.186368
Unit Labor Cost [ULCNFB]                         -12.305755

                                                       Min/Max Dates
Payroll Employment [PAYEMS]                      Mar-2009 / May-2010
Job Openings [JTSJOL]                            Feb-2001 / Jan-2003
Consumer Price Index [CPIAUCSL]                  Nov-2008 / Sep-2005
Durable Goods Orders [DGORDER]                   Aug-2014 / Jul-2014
Retail Sales [RSAFS]                             Nov-2008 / Oct-2001
Unemployment Rate [UNRATE]                       Dec-2010 / Feb-2009
Housing Starts [HOUST]                           Feb-2015 / Oct-2016
Industrial Production [INDPRO]                   Sep-2008 / May-2010
Personal Income [DSPIC96]                        Jan-2013 / May-2008
Exports [BOPTEXP]                                Sep-2001 / Mar-2011
Imports [BOPTIMP]                                Nov-2008 / Mar-2015
Construction Spending [TTLCONS]                  Jan-2011 / Apr-2015
Import Price Index [IR]                          Nov-2008 / Nov-2007
Core Consumer Price Index [CPILFESL]             Jan-2010 / Jun-2001
Core PCE Price Index [PCEPILFE]                  Sep-2001 / Oct-2001
PCE Price Index [PCEPI]                          Nov-2008 / Sep-2005
Building Permits [PERMIT]                        Jul-2008 / Jun-2008
Capacity Utilization Rate [TCU]                  Sep-2008 / May-2010
Business Inventories [BUSINV]                    Dec-2008 / Mar-2011
Export Price Index [IQ]                          Nov-2008 / Mar-2008
Empire State Mfg Index [GACDISA066MSFRBNY]       Feb-2009 / Apr-2004
Real Consumption Spending [PCEC96]               Sep-2009 / Oct-2001
Philadelphia Fed Mfg Index [GACDFSA066MSFRBPHI]  Nov-2008 / Mar-2011
Real Gross Domestic Product [GDPC1]              Dec-2008 / Jun-2000
Unit Labor Cost [ULCNFB]                         Mar-2009 / Mar-2000
creating file .pickles/ResDFM-iter_V-2016-12-16-M-5000_T-0.0001-hash-4992051.pickle




Table 3: Block Loading Structure
                             Global  Soft  Real  Labor
Payroll Employment                1     0     0      1
Job Openings                      1     0     0      1
Consumer Price Index              1     0     0      0
Durable Goods Orders              1     0     1      0
Retail Sales                      1     0     1      0
Unemployment Rate                 1     0     0      1
Housing Starts                    1     0     1      0
Industrial Production             1     0     1      0
Personal Income                   1     0     1      0
Exports                           1     0     1      0
Imports                           1     0     1      0
Construction Spending             1     0     1      0
Import Price Index                1     0     0      0
Core Consumer Price Index         1     0     0      0
Core PCE Price Index              1     0     0      0
PCE Price Index                   1     0     0      0
Building Permits                  1     0     1      0
Capacity Utilization Rate         1     0     1      0
Business Inventories              1     0     1      0
Export Price Index                1     0     0      0
Empire State Mfg Index            1     1     0      0
Real Consumption Spending         1     0     1      0
Philadelphia Fed Mfg Index        1     1     0      0
Real Gross Domestic Product       1     0     1      0
Unit Labor Cost                   1     0     0      1


Estimating the dynamic factor model (DFM)


Now running the 10th iteration of max 5000
Loglik: -1287.2819969688949 (% Change: -0.10309234836355456)
Now running the 20th iteration of max 5000
Loglik: -1280.0906937601717 (% Change: -0.03478665709874121)
Now running the 30th iteration of max 5000
Loglik: -1276.963003901566 (% Change: -0.018844814758985223)
Now running the 40th iteration of max 5000
Loglik: -1274.8183311707276 (% Change: -0.017175564425111346)
Now running the 50th iteration of max 5000
Loglik: -1271.4978300299626 (% Change: -0.03367339418461606)
Now running the 60th iteration of max 5000
Loglik: -1268.7716399003991 (% Change: -0.018075626769474534)
Now running the 70th iteration of max 5000
Loglik: -1266.5967687459845 (% Change: -0.01588790553514619)
Now running the 80th iteration of max 5000
Loglik: -1264.878005220685 (% Change: -0.011631866181664608)
Successful: Convergence at 86 interations

 Table 4: Factor Loadings for Monthly Series
                              Global      Soft      Real     Labor
Payroll Employment          0.251672  0.000000  0.000000  0.604383
Job Openings                0.094676  0.000000  0.000000  0.320691
Consumer Price Index        0.250423  0.000000  0.000000  0.000000
Durable Goods Orders        0.121073  0.000000  0.024728  0.000000
Retail Sales                0.217847  0.000000  0.513570  0.000000
Unemployment Rate          -0.183191  0.000000  0.000000 -0.728816
Housing Starts              0.101131  0.000000  0.278031  0.000000
Industrial Production       0.250104  0.000000 -0.150089  0.000000
Personal Income            -0.001120  0.000000  0.166781  0.000000
Exports                     0.277024  0.000000 -0.030799  0.000000
Imports                     0.273036  0.000000 -0.061968  0.000000
Construction Spending       0.128506  0.000000  0.272492  0.000000
Import Price Index          0.283659  0.000000  0.000000  0.000000
Core Consumer Price Index   0.035928  0.000000  0.000000  0.000000
Core PCE Price Index        0.125721  0.000000  0.000000  0.000000
PCE Price Index             0.273991  0.000000  0.000000  0.000000
Building Permits            0.094687  0.000000  0.393857  0.000000
Capacity Utilization Rate   0.248187  0.000000 -0.164393  0.000000
Business Inventories        0.261178  0.000000 -0.263408  0.000000
Export Price Index          0.261052  0.000000  0.000000  0.000000
Empire State Mfg Index      0.249436  0.674644  0.000000  0.000000
Real Consumption Spending   0.135171  0.000000  0.526470  0.000000
Philadelphia Fed Mfg Index  0.261852  0.738313  0.000000  0.000000

 Table 5: Quarterly Loadings Sample (Global Factor)
                              f1_lag0   f1_lag1   f1_lag2   f1_lag3   f1_lag4
Real Gross Domestic Product  0.034819  0.069638  0.104458  0.069638  0.034819
Unit Labor Cost              0.006899  0.013797  0.020696  0.013797  0.006899

 Table 6: Autoregressive Coefficients on Factors
        AR_Coefficient  Variance_Residual
Global        0.838420           1.419815
Soft          0.867386           0.198935
Real         -0.052164           1.121701
Labor         0.952030           0.048065

 Table 7: Autoregressive Coefficients on Idiosyncratic Component
                             AR_Coefficient  Variance_Residual
Payroll Employment                 0.459852           0.249082
Job Openings                      -0.448117           0.760785
Consumer Price Index               0.331015           0.584844
Durable Goods Orders              -0.425301           0.754796
Retail Sales                      -0.351384           0.328093
Unemployment Rate                 -0.175835           0.613996
Housing Starts                    -0.470791           0.711866
Industrial Production             -0.057676           0.651311
Personal Income                   -0.188452           0.934817
Exports                           -0.319997           0.519114
Imports                           -0.432018           0.477382
Construction Spending              0.331079           0.780902
Import Price Index                 0.455007           0.389914
Core Consumer Price Index          0.212058           0.927698
Core PCE Price Index              -0.127516           0.916250
PCE Price Index                    0.281708           0.554107
Building Permits                  -0.306463           0.807008
Capacity Utilization Rate         -0.045904           0.635863
Business Inventories               0.646185           0.329828
Export Price Index                 0.262269           0.539899
Empire State Mfg Index             0.563333           0.222618
Real Consumption Spending         -0.346577           0.453816
Philadelphia Fed Mfg Index         0.062339           0.138741
Real Gross Domestic Product       -0.444803           0.046925
Unit Labor Cost                   -0.894439           0.086653
Function run took 20.3908 seconds to run.

In [2]:

print(result_dict.keys())

dict_keys(['fig', 'real_impacts', 'data_released', 'news_table'])

In [3]:
result_dict['real_impacts']

          Forecast    Actual    Weight    Impact
DGORDER  -1.832871 -4.598821  0.007409 -0.020493
DSPIC96   0.174263 -0.050908  0.011456 -0.002580
PCEPILFE  0.142310  0.004467  0.237833 -0.032784
PCEPI     0.173086  0.041284  0.264582 -0.034872
PCEC96    0.188655  0.144587  0.367998 -0.016217

In [4]:
result_dict['data_released']

array([False, False, False,  True, False, False, False, False,  True,
       False, False, False, False, False,  True,  True, False, False,
       False, False, False,  True, False, False, False])

In [5]:
result_dict['news_table']

                    Forecast    Actual    Weight    Impact
PAYEMS                   NaN       NaN       NaN       NaN
JTSJOL                   NaN       NaN       NaN       NaN
CPIAUCSL                 NaN       NaN       NaN       NaN
DGORDER            -1.832871 -4.598821  0.007409 -0.020493
RSAFS                    NaN       NaN       NaN       NaN
UNRATE                   NaN       NaN       NaN       NaN
HOUST                    NaN       NaN       NaN       NaN
INDPRO                   NaN       NaN       NaN       NaN
DSPIC96             0.174263 -0.050908  0.011456 -0.002580
BOPTEXP                  NaN       NaN       NaN       NaN
BOPTIMP                  NaN       NaN       NaN       NaN
TTLCONS                  NaN       NaN       NaN       NaN
IR                       NaN       NaN       NaN       NaN
CPILFESL                 NaN       NaN       NaN       NaN
PCEPILFE            0.142310  0.004467  0.237833 -0.032784
PCEPI               0.173086  0.041284  0.264582 -0.034872
PERMIT                   NaN       NaN       NaN       NaN
TCU                      NaN       NaN       NaN       NaN
BUSINV                   NaN       NaN       NaN       NaN
IQ                       NaN       NaN       NaN       NaN
GACDISA066MSFRBNY        NaN       NaN       NaN       NaN
PCEC96              0.188655  0.144587  0.367998 -0.016217
GACDFSA066MSFRBPHI       NaN       NaN       NaN       NaN
GDPC1                    NaN       NaN       NaN       NaN
ULCNFB                   NaN       NaN       NaN       NaN

In [6]:
result_dict['fig']